# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'convocatoriaCursos' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for convocatoriaCursos
   pod 'Firebase/Database'

  target 'convocatoriaCursosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'convocatoriaCursosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
